### ISSUE TITLE
Investigate new base builder for buildpacks

### ISSUE THREAD

**Issue by ipmb** [apppackio/apppack-codebuild-image#5]
Heroku 22 builders have some incompatibilities we need to consider around CNB/non-CNB buildpacks.

https://github.com/heroku/builder/issues/298#issuecomment-1306910995
https://github.com/heroku/buildpacks-python/issues/14

There is also a new version of the 20 builder now https://github.com/heroku/buildpacks-python/pull/117

**Comment by edmorley** [comment]
Hi Peter - hope you are well.

I just wanted to let you know that the `heroku/buildpacks:20` and `heroku/builder-classic:22` CNB builder images are now deprecated and output a warning to the build log as of https://github.com/heroku/cnb-builder-images/pull/429.

I see the following references to these under the `apppackio` org:
https://github.com/search?q=org%3Aapppackio%20(heroku%2Fbuilder-classic%20OR%20heroku%2Fbuildpacks)&type=code

**Comment by edmorley** [comment]
It also looks like the buildpacks list here is out of date:
https://github.com/apppackio/apppack-codebuild-image/blob/f96edcb418913140598af0cf9fd3c14e16f054ce/builder/build/appjson.go#L35-L54

**Comment by ipmb** [comment]
Thanks @edmorley!

How are you handling migration between the CNB Python buildpacks and the classic shimmed one? The main thing that has held back a blanket upgrade to the 22/CNB stack is that (afaik), it is not backwards compatible. `post-compile` comes to mind, but I think there may be others.

**Comment by edmorley** [comment]
I agree there are a handful of things that aren't backwards compatible at the moment wrt the Python buildpack - I'm currently tracking these via the parity label here:
https://github.com/heroku/buildpacks-python/issues?q=is%3Aissue+is%3Aopen+label%3A%22classic+buildpack+parity%22

Regarding `bin/pre_compile` / `bin/post_compile` I'm leaning towards not supporting it for the reasons in https://github.com/heroku/buildpacks-python/issues/14. However, if I don't support it, I will add an error/warning to the CNB to help with migration UX (of migrating to an inline buildpack or script reference in `project.toml`).

**Comment by ipmb** [comment]
@edmorley thanks for your work here. Opening issues downstream is above-and-beyond 😄 

I do have concern that deprecating the legacy buildpack before the new one is at parity or an official migration doc exists will confuse a lot of users.

I expect many users will see the deprecation warning, upgrade as directed, then find out the new builder is incompatible, possibly only after deploying their application.

**Comment by edmorley** [comment]
> I do have concern that deprecating the legacy buildpack before the new one is at parity or an official migration doc exists will confuse a lot of users.

I agree there are still a couple of rough edges for some of the Heroku CNBs - they are high up our list to address. One of the issues is that from our side Heroku's CNB images are effectively pre-beta (they are not used for anything within Heroku itself at the moment), but some non-Heroku platforms are using them in production already. We're doing our best to be respectful of that, but we need feedback on the CNBs, and one of the best ways to get more feedback is to nudge people over from the shimmed images (many of whom don't even know they are using a "held together with tape and glue" shimmed buildpack). If the Heroku stack EOLs are anything to go by, people take ages to migrate to anything new, so I wanted to start the deprecation process sooner rather than later.

**Comment by edmorley** [comment]
Oh meant to say - another forcing function here is:
https://github.com/heroku/cnb-shim/issues/69#issuecomment-1785872842

**Comment by edmorley** [comment]
The legacy shimmed builder image deprecation warnings were upgraded to errors this morning:
https://github.com/heroku/cnb-builder-images/pull/478

The errors can be skipped by setting `ALLOW_EOL_SHIMMED_BUILDER=1`.

**Comment by edmorley** [comment]
The way the deprecation warnings (and now errors) were implemented was via a buildpack added to every group in the builder's default buildpack detection ordering. If a manual buildpack ordering is passed (eg via `project.toml`) to override the builder's default, then the deprecation/error buildpack won't run.

Longer term there is talk of the upstream CNB project supporting metadata in the builder that the platform (eg Pack CLI, or any other equivalent) could use to display deprecation warnings - however, for now I couldn't think of a better way of implementing the warnings.

**Comment by edmorley** [comment]
(Although in practice, it's the "blog post written 2 years ago that tells people to `pack build --builder heroku/buildpacks:20` case that we most want to prevent people from using accidentally; and that case will error)

**Comment by ipmb** [comment]
Based on the flurry of support requests that just came through, I'm guessing this new approach means that this is no longer true? https://github.com/apppackio/apppack-codebuild-image/issues/5#issuecomment-2004145127

> If a manual buildpack ordering is passed (eg via project.toml) to override the builder's default, then the deprecation/error buildpack won't run.

**Comment by edmorley** [comment]
Yeah:
https://github.com/apppackio/apppack-codebuild-image/issues/5#issuecomment-2018508002

**Comment by ipmb** [comment]
We will switch our default buildpack to `heroku/builder:22` on May 1. Announcement here: https://apppack.io/blog/upgrading-our-default-heroku-stack-for-buildpacks/

Pending PR: https://github.com/apppackio/apppack-codebuild-image/pull/6

I had hoped that there would be full feature parity between the shimmed and CNB buildpacks before we made the switch, but the EOL warnings/errors put us between a rock and a hard place.
